### ISSUE TITLE
Source files still locked after processing is finished

### ISSUE THREAD

**Issue by Pairan** [kirek007/ws-osd-py#14]
After the PNG files for the overlay have been created and the process finishes, the video/osd files are still locked by Python as it didn't seem to close/flush/whatever the file (handles).

perhaps this could be fixed to get access again after the job is done (and without new file assigment or quitting the programm)

**Comment by kirek007** [comment]
That's not possible, because handles are needed to generate a preview. So you have to provide different files or close the application.
