### ISSUE TITLE
make run don't work

### ISSUE THREAD

**Issue by jorgermp** [kirek007/ws-osd-py#2]
I download the latest version from git, but when I try make run I have this error, I'm using Ubuntu 22.04 with Python 3.10 and I add attrdict to requirements.txt
`➜  ws-osd-py git:(main) ✗ make run            
./.venv/bin/pip install -r requirements.txt
Collecting attrdict
  Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Collecting altgraph==0.17.3
  Using cached altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
Collecting ffmpeg-python==0.2.0
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting future==0.18.2
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.24.1
  Using cached numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting opencv-python==4.6.0.66
  Using cached opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
Collecting pefile==2022.5.30
  Using cached pefile-2022.5.30.tar.gz (72 kB)
  Preparing metadata (setup.py) ... done
Collecting Pillow==9.3.0
  Using cached Pillow-9.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.3 MB)
Collecting pyinstaller==5.7.0
  Using cached pyinstaller-5.7.0-py3-none-manylinux2014_x86_64.whl (649 kB)
Collecting pyinstaller-hooks-contrib==2022.14
  Using cached pyinstaller_hooks_contrib-2022.14-py2.py3-none-any.whl (252 kB)
Collecting Pypubsub==4.0.3
  Using cached Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Collecting pywin32-ctypes==0.2.0
  Using cached pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wxPython==4.2.0
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n87c4cfj/wxpython_0a1de7204f67484e873b873f38bd48f3/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-n87c4cfj/wxpython_0a1de7204f67484e873b873f38bd48f3/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile.venv:233: .venv/bin/.initialized-with-Makefile.venv] Error 1
`

**Comment by kirek007** [comment]
I don't know why but this is broken in wxPython lib :( 
You can try installing wxPython from whl file.
Download `https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl` and install using `pip install <file_name>`.
Don't forget to activate venv before with `source .venv/bin/activate`

Related issue: https://github.com/wxWidgets/Phoenix/issues/2325
