### ISSUE TITLE
how to change python version on macos

### ISSUE THREAD

**Issue by Radla** [kirek007/ws-osd-py#24]
Hi,
i have the problem that my MacMini M1 has the python3 v3.8 binary in the /usr/bin directory. I can not change or delete it.

So i installed the v3.11.1 pkg from www.python.org which did not work. After some google search i installed the same version with pyenv, but it still not work.

my current setup:
`ralle@MMM1 ws-osd-py % which python3
/Users/ralle/.pyenv/shims/python3
ralle@MMM1 ws-osd-py % python3 --version
Python 3.11.1`

but the 'make run' command still uses the /usr/bin version:

`ralle@MMM1 ws-osd-py % make run     
Python 3.8.2 (default, Apr  8 2021, 23:19:18) [Clang 12.0.5 (clang-1205.0.22.9)]
pip 22.3.1 from /Volumes/Samsung_T5/dox/Drohnen/ws-osd-py/.venv/lib/python3.8/site-packages/pip (python 3.8)
venv: ./.venv
./.venv/bin/python -c 'import sys; valid=(sys.version_info > (3,9) and sys.version_info < (3,11)); sys.exit(0) if valid else sys.exit(1)' || (echo "Python 3.10 is required"; exit 1)
Python 3.10 is required
make: *** [run] Error 1
`
the PATH looks like:
`ralle@MMM1 ws-osd-py % echo $path
/Users/ralle/.pyenv/shims /opt/homebrew/bin /usr/local/bin /Library/Frameworks/Python.framework/Versions/3.11/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Frameworks/Python.framework/Versions/3.11`

Somebody has an idea how i get rid of the old v3.8?

**Comment by kirek007** [comment]
Sorry, but I don't have enough macos experience to help you with it. 
You can try to ask for help at Walksnail FB page to Discord server, there are few folks that are running it on macOS
