### ISSUE TITLE
Zoom and offset sliders have no effect on the output

### ISSUE THREAD

**Issue by WereWolfPL** [kirek007/ws-osd-py#26]
In the latest pre-release version: https://github.com/kirek007/ws-osd-py/releases/tag/master-f9342f2523c7bf0e6a5d4871e4be7d01a2a1f6d2

The sliders have no effect on generated images and video.
The preview window works fine, but in the output files osd is in the default position.

**Comment by kirek007** [comment]
Can you provide any log from console?

**Comment by WereWolfPL** [comment]
> Can you provide any log from console?

It doesn't give any error, just standard info, like: 
```
DEBUG:root:Preview update requested.
DEBUG:root:Slider updated.
DEBUG:root:Preview update requested.
DEBUG:root:Slider updated.
DEBUG:root:Preview update requested.
DEBUG:root:Current: 200/8719 (fps: 315)
DEBUG:root:Current: 400/8719 (fps: 294)
```

The latest version (0.8 beta) didn't fix it for me. No matter what I set on the sliders, the generated osd looks like all the settings were set to 0.

**Comment by kirek007** [comment]
Then I need as much details as you can provide ;)
What operating system ?
Is it happening for all video files?
Screen of application
Whole log from console
If this is happening only for some files then I need them.

W dniu wt., 31.01.2023 o 09:09 Marcin Lubke ***@***.***>
napisał(a):

**Comment by WereWolfPL** [comment]
Ok, so...
System: windows 10 64-bit
It's happening for all of my files. I'm not sure if it matters, but I use walksnail vrx module with full size vtx. Tested with firmware 29.33.16 and 31.36.8(beta). It's definitely something with generating .png files, rendering of the video doesn't matter here.

Here are some screenshots - app's window (I tested it with different settings), one of generated frames and some screenshot of the video, full console log and two of my sample .osd files.

Let me know if I can send any more details.

![ws_osd_gen_2023-01-31_09-47-48](https://user-images.githubusercontent.com/23664608/215738107-ffa8cdbb-2b7e-4077-a293-5e67d4472eb0.png)
![ws_000000660](https://user-images.githubusercontent.com/23664608/215738557-31237fa3-50eb-45d8-b0fc-299e624b8468.png)
![AvatarG0011_generated_osd mp4_20230131_101155 599](https://user-images.githubusercontent.com/23664608/215738176-7f338564-2a78-4e75-90ca-3e83ea26fe58.jpg)
[log.txt](https://github.com/kirek007/ws-osd-py/files/10545548/log.txt)
[osd_files.zip](https://github.com/kirek007/ws-osd-py/files/10545552/osd_files.zip)

**Comment by kirek007** [comment]
Okey, now I know what's going on. Definitely a bug.
