### ISSUE TITLE
distance on SRT not updating

### ISSUE THREAD

**Issue by iamwinq** [kirek007/ws-osd-py#28]
I tried rendering the flight from my arduplane setup, you can see here that distance from home is already around 1.5km, but the distance on the SRT overlay is still 0... upon checking the SRT file, I was able to validate that the distance is 0...

![image](https://user-images.githubusercontent.com/95698959/213912017-4d997566-1f38-4861-8222-8670004929e4.png)

**Comment by WereWolfPL** [comment]
Is this with walksnail's high bitrate mode? If yes than it's walksnail's bug, not the overlay tool.

On 25Mbps the distance works fine, but on 50Mbps it shows 0 during the whole flight (at least with my setup).

**Comment by iamwinq** [comment]
oh, right, this is on high bitrate... thanks for clarifiying this. should i close this issue i posted?
