### ISSUE TITLE
Hiding out unwanted OSD elements

### ISSUE THREAD

**Issue by Pairan** [kirek007/ws-osd-py#3]
I just came up with something I need to do in several and almost any video: Hiding some items from the OSD.
As I'm not good in Python so I will write the statement in normal text:

**if `index+page` (= the osd item) is part of the `list/array of unwanted items` then skip the render for it**

Examples could be the usual favorites like `GPS LAT/LON`, `DISTANCE`, `ALT` etc ... 

I will just assume it would fit in here :

```python
    def __convert_to_glyphs(self):
        glyphs_arr = []
        for x in range(0, len(self.rawData), 2):
            index, page = unpack("<BB", self.rawData[x:x + 2])
            glyph = self.font.get_glyph(index + page * 255 )
            glyphs_arr.append(glyph)

        return glyphs_arr
```
Maybe this would be a handy little enhancement.

**Comment by kirek007** [comment]
Hey, that's way more complicated. Especially that i don't know what element is drawn where. All I have is draw image X in place Y,Z. But will think more about it ;)

**Comment by Pairan** [comment]
This should help us in that case 

https://github.com/iNavFlight/inav-configurator/blob/master/resources/osd/INAV%20Character%20Map.md
