### ISSUE TITLE
Time out of sync .srt and .osd by 3-4sec

### ISSUE THREAD

**Issue by aLDime** [kirek007/ws-osd-py#34]
![ws_000004130_bug](https://user-images.githubusercontent.com/5435764/218021045-e3957ab7-a4c0-4a54-8e49-8f741eaa0833.png)
I don't think comments are needed.

**Comment by kirek007** [comment]
Please use latest version 0.9, it's fixed there

pt., 10 lut 2023, 07:42 użytkownik Dmitry ***@***.***>
napisał:

**Comment by aLDime** [comment]
> Please use latest version 0.9, it's fixed there pt., 10 lut 2023, 07:42 użytkownik Dmitry ***@***.***> napisał:
> […](#)
>*>

oh sorry.. how i missed that..
