### ISSUE TITLE
Burn In Walksnail SRT file as an optional feature

### ISSUE THREAD

**Issue by TowkayNew** [kirek007/ws-osd-py#6]
Other than OSD information from FC, the OSD information from VRX (.srt file) is also useful. 

It will be awesome if there is an optional feature to burn in these .srt information along with the .osd file.

Thanks for developing!

**Comment by kirek007** [comment]
Hey, thanks for input ;) 
I'm already working on that .. problem is that it's very hard to make it look nice and matching used font.

**Comment by kirek007** [comment]
Beta code is already available here, you can try it if you know how :)
https://github.com/kirek007/ws-osd-py/tree/add-srt-overlay
