### ISSUE TITLE
WTFOS OSD compatibility

### ISSUE THREAD

**Issue by Schalonsus** [kirek007/ws-osd-py#8]
Great project, would it be a lot of work to integrate the WTFOS OSD overlay?

https://github.com/fpv-wtf/msp-osd
https://github.com/Knifa/osd-dump-tools

Thank you

**Comment by kirek007** [comment]
Hey, Thanks for suggestions.
Why would you like to reimplements it in my project. Knifa's project is very well maintained and up to date. 
Currently I do not consider touching DJI stuff, because I don't even have gear anymore ;)

**Comment by Schalonsus** [comment]
Oh thanks for the hint, didn't realise its a ready to use program of Knifa, so this issue can be closed
